# Generated by Django 5.2.4 on 2025-07-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busekus', '0005_alter_meep_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
